package malpefile

const (
	BYTE  = 1
	WORD  = 2
	DWORD = 4

	DS_SETFONT = 0x40

	DIALOG_LEAD      = DWORD + DWORD + WORD + WORD + WORD + WORD + WORD
	DIALOG_ITEM_LEAD = DWORD + DWORD + WORD + WORD + WORD + WORD + WORD

	DIALOGEX_LEAD       = WORD + WORD + DWORD + DWORD + DWORD + WORD + WORD + WORD + WORD + WORD
	DIALOGEX_TRAIL      = WORD + WORD + BYTE + BYTE
	DIALOGEX_ITEM_LEAD  = DWORD + DWORD + DWORD + WORD + WORD + WORD + WORD + DWORD
	DIALOGEX_ITEM_TRAIL = WORD
)

var ITEM_TYPES = map[int]string{
	0x80: "BUTTON",
	0x81: "EDIT",
	0x82: "STATIC",
	0x83: "LIST BOX",
	0x84: "SCROLL BAR",
	0x85: "COMBO BOX",
}
